<div class="jumbotron jumbotron-fluid bg-Altair-grey text-white">
    <div class="row justify-content-center p-4">
        <div class="card-grey p-3" style="box-shadow: <?= $GLOBALS['STYLE']['boxShadow'] ?>; background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] . 'd9' ?>; color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>;"> 
            <h3 class="mt-5">Ajouter ou modifier vos informations</h3>
            <form method="POST" action="" class="form">
                <div class="form-row my-5">
                    <div class="form-group col-md-4">
                        <label for="inputRegion">Région</label>
                        <select class="browser-default custom-select" id="inputRegion" name="region" required>
                            <option value=""><?= $region = (empty($adminInfo['region'])) ? 'Région' : $adminInfo['region'] ?></option>
                        <?php foreach($regions as $region): ?>
                            <option value="<?= $region ?>"><?= $region ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputDepartement">Département</label>
                        <select class="browser-default custom-select" id="inputDepartement" name="departement" required>
                            <option value=""><?= $departement = (empty($adminInfo['departement'])) ? 'Département' : $adminInfo['departement'] ?></option>
                        <?php foreach($dept as $key => $d): ?>
                            <option value="<?= $key . '  ' . $d ?>"><?= $key . '  ' . $d ?></option>
                        <?php endforeach;?>
                    </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputVille">Ville</label>
                        <input type="text" class="form-control" id="inputVille" placeholder="Ville" name="ville" value="<?= $ville = (empty($adminInfo['ville'])) ? '' : $adminInfo['ville'] ?>">
                    </div>
                    <div class="form-group col-md-12">
                        <label for="inputAdresse">Adresse</label>
                        <input type="text" class="form-control" id="inputAdresse" placeholder="Adresse" name="adresse" value="<?= $adresse = (empty($adminInfo['adresse'])) ? '' : $adminInfo['adresse'] ?>">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="inputPhone">Téléphone</label>
                        <input type="tel" class="form-control" id="inputPhone" pattern="[0-9]{2}[0-9]{2}[0-9]{2}[0-9]{2}[0-9]{2}" name="telephone" value="<?= $telephone = (empty($adminInfo['telephone'])) ? '' : $adminInfo['telephone'] ?>">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputjob">Profession</label>
                        <input type="text" class="form-control" id="inputjob" name="job" value="<?= $societe = (empty($adminInfo['job'])) ? '' : $adminInfo['job'] ?>">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputSociety">Socièté</label>
                        <input type="text" class="form-control" id="inputSociety" name="societe" value="<?= $societe = (empty($adminInfo['societe'])) ? '' : $adminInfo['societe'] ?>">
                    </div>
                    <div class="form-group col-md-12">
                        <label for="inputwebsite">Site Web</label>
                        <input type="text" class="form-control" id="inputwebsite" name="website" value="<?= $website = (empty($adminInfo['website'])) ? '' : $adminInfo['website'] ?>">
                    </div>
                </div>
                <div id="rs">
                    <div class="form-row mt-5 mb-4">
                        <h5 class="text-grey">Choisissez jusqu'à 4 réseaux sociaux</h5>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputFacebook">Facebook</label>
                            <input type="url" class="form-control" id="inputFacebook" name="facebook" value="<?= $facebook = (empty($adminInfo['facebook'])) ? '' : $adminInfo['facebook'] ?>" onfocusout="checkRs()">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputLinkedIn">LinkedIn</label>
                            <input type="url" class="form-control" id="inputLinkedIn" name="linkedin" value="<?= $linkedin = (empty($adminInfo['linkedin'])) ? '' : $adminInfo['linkedin'] ?>" onfocusout="checkRs()">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputVimeo">Vimeo</label>
                            <input type="url" class="form-control" id="inputVimeo" name="vimeo" value="<?= $viadeo = (empty($adminInfo['vimeo'])) ? '' : $adminInfo['vimeo'] ?>" onfocusout="checkRs()">
                        </div>            
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputSkype">Skype</label>
                            <input type="text" class="form-control" id="inputSkype" name="skype" value="<?= $skype = (empty($adminInfo['skype'])) ? '' : $adminInfo['skype'] ?>" onfocusout="checkRs()">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputGoogle">Google +</label>
                            <input type="url" class="form-control" id="inputGoogle" name="google" value="<?= $google = (empty($adminInfo['google'])) ? '' : $adminInfo['google'] ?>" onfocusout="checkRs()">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputYoutube">Youtube</label>
                            <input type="url" class="form-control" id="inputYoutube" name="youtube" value="<?= $youtube = (empty($adminInfo['youtube'])) ? '' : $adminInfo['youtube'] ?>" onfocusout="checkRs()">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputInstagram">Instagram</label>
                            <input type="url" class="form-control" id="inputInstagram" name="instagram" value="<?= $instagram = (empty($adminInfo['instagram'])) ? '' : $adminInfo['instagram'] ?>" onfocusout="checkRs()">
                        </div>            
                        <div class="form-group col-md-4">
                            <label for="inputPinterest">Pinterest</label>
                            <input type="text" class="form-control" id="inputPinterest" name="pinterest" value="<?= $pinterest = (empty($adminInfo['pinterest'])) ? '' : $adminInfo['pinterest'] ?>" onfocusout="checkRs()">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputSnapchat">Snapchat</label>
                            <input type="url" class="form-control" id="inputSnapchat" name="snapchat" value="<?= $snapchat = (empty($adminInfo['snapchat'])) ? '' : $adminInfo['snapchat'] ?>" onfocusout="checkRs()">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputTwitter">Twitter</label>
                            <input type="url" class="form-control" id="inputTwitter" name="twitter" value="<?= $twitter = (empty($adminInfo['twitter'])) ? '' : $adminInfo['twitter'] ?>" onfocusout="checkRs()">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputSoundCloud">SoundCloud</label>
                            <input type="url" class="form-control" id="inputSoundCloud" name="soundcloud" value="<?= $soundcloud = (empty($adminInfo['soundcloud'])) ? '' : $adminInfo['soundcloud'] ?>" onfocusout="checkRs()">
                        </div>            
                        <div class="form-group col-md-4">
                            <label for="inputSpotify">Spotify</label>
                            <input type="text" class="form-control" id="inputSpotify" name="spotify" value="<?= $spotify = (empty($adminInfo['spotify'])) ? '' : $adminInfo['spotify'] ?>" onfocusout="checkRs()">
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-end mt-5">
                    <?php 
                        if($_SESSION['auth']['role'] === 'admin' || $_SESSION['auth']['role'] === 'superAdmin'):
                    ?>
                    <a href="<?= route_to_url('adminPro') ?>?id=<?= $id ?>" class="btn grey darken-1">
                        Mes infos Pro
                    </a>
                        <?php endif; ?>
                    <a href="<?= route_to_url('fullAccount') ?>?id=<?= $id ?>" class="btn grey darken-1">
                        Mon compte
                    </a>
                    <button type="submit" class="btn elegant-color">Enregistrer / Modifier</button>
                </div>
            </form>
        </div>
    </div>  
</div>
<script>
    const allRS = document.getElementById('rs');
    const rsInput = allRS.querySelectorAll('input');
    const inputValue = [];
    let result = [];

    function ifAsRs(){
        rsInput.forEach(element => inputValue.push(element.value));
        result = inputValue.filter(rs => rs.length != "");
        disableInput(result);        
    }
    // checkRs(); 
    function checkRs(){
        data = event.target.value;
        result.push(data);
        disableInput(result);        

    }   
    
    function disableInput(result){
        if(result.length >= 4){
            rsInput.forEach(function(element){
                if(element.value == ""){
                    element.setAttribute('disabled', "");
                }
            })
        }
    }
    ifAsRs();
    
</script>