<div class="d-flex align-items-center justify-content-center myCards" style="background: url(<?= URL_SOURCES."/images/creative-light.jpg" ?>)">
    <div class="card p-3" style="box-shadow: <?= $GLOBALS['STYLE']['boxShadow'] ?>; background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] . 'd9' ?>; color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>;"> 
        <h3 class="mt-5" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: 1px 1px 2px red, 0 0 1em blue, 0 0 0.2em blue;">Ajouter ou modifier vos informations</h3>
        <form method="POST" action="" class="form">
            <div class="form-row my-5">
                <div class="form-group col-md-4">
                <select class="browser-default custom-select" id="inputRegion" name="region">
                    <option selected><?= $region = (empty($adminInfo['region'])) ? 'Région' : $adminInfo['region'] ?></option>
                <?php foreach($regions as $region): ?>
                    <option value="<?= $region ?>"><?= $region ?></option>
                    <?php endforeach; ?>
                </select>
                </div>
                <div class="form-group col-md-4">
                <select class="browser-default custom-select" id="inputDepartement" name="departement">
                    <option selected><?= $departement = (empty($adminInfo['departement'])) ? 'Département' : $adminInfo['departement'] ?></option>
                <?php foreach($dept as $key => $d): ?>
                    <option value="<?= $key . '  ' . $d ?>"><?= $key . '  ' . $d ?></option>
                <?php endforeach;?>
                </select>
                </div>
                <div class="form-group col-md-4">
                <input type="text" class="form-control" id="inputVille" placeholder="Ville" name="ville" value="<?= $ville = (empty($adminInfo['ville'])) ? '' : $adminInfo['ville'] ?>">
                </div>
                <div class="form-group col-md-12">
                <input type="text" class="form-control" id="inputAdresse" placeholder="Adresse" name="adresse" value="<?= $adresse = (empty($adminInfo['adresse'])) ? '' : $adminInfo['adresse'] ?>">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label for="inputSociety">Téléphone</label>
                    <input type="tel" class="form-control" id="inputPhone" pattern="[0-9]{2}[0-9]{2}[0-9]{2}[0-9]{2}[0-9]{2}" name="telephone" value="<?= $telephone = (empty($adminInfo['telephone'])) ? '' : $adminInfo['telephone'] ?>">
                </div>
                <div class="form-group col-md-3">
                    <label for="inputSociety">Socièté</label>
                    <input type="text" class="form-control" id="inputSociety" name="societe" value="<?= $societe = (empty($adminInfo['societe'])) ? '' : $adminInfo['societe'] ?>">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputSociety">Site Web</label>
                    <input type="text" class="form-control" id="inputSociety" name="website" value="<?= $website = (empty($adminInfo['website'])) ? '' : $adminInfo['website'] ?>">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label for="inputFacebook">Facebook</label>
                    <input type="url" class="form-control" id="inputFacebook" name="facebook" value="<?= $facebook = (empty($adminInfo['facebook'])) ? '' : $adminInfo['facebook'] ?>">
                </div>
                <div class="form-group col-md-3">
                    <label for="inputLinkedIn">LinkedIn</label>
                    <input type="url" class="form-control" id="inputLinkedIn" name="linkedin" value="<?= $linkedin = (empty($adminInfo['linkedin'])) ? '' : $adminInfo['linkedin'] ?>">
                </div>
                <div class="form-group col-md-3">
                    <label for="inputViadeo">Viadeo</label>
                    <input type="url" class="form-control" id="inputViadeo" name="viadeo" value="<?= $viadeo = (empty($adminInfo['viadeo'])) ? '' : $adminInfo['viadeo'] ?>">
                </div>            
                <div class="form-group col-md-3">
                    <label for="inputSkype">Skype</label>
                    <input type="text" class="form-control" id="inputSkype" name="skype" value="<?= $skype = (empty($adminInfo['skype'])) ? '' : $adminInfo['skype'] ?>">
                </div>
            </div>
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-warning">Enregistrer / Modifier</button>
                <a href="<?= route_to_url('account') ?>" class="btn peach-gradient infobulle">
                    <svg class="bi bi-house" width="2em" height="2em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M9.646 3.146a.5.5 0 01.708 0l6 6a.5.5 0 01.146.354v7a.5.5 0 01-.5.5h-4.5a.5.5 0 01-.5-.5v-4H9v4a.5.5 0 01-.5.5H4a.5.5 0 01-.5-.5v-7a.5.5 0 01.146-.354l6-6zM4.5 9.707V16H8v-4a.5.5 0 01.5-.5h3a.5.5 0 01.5.5v4h3.5V9.707l-5.5-5.5-5.5 5.5z" clip-rule="evenodd"/>
                        <path fill-rule="evenodd" d="M15 4.5V8l-2-2V4.5a.5.5 0 01.5-.5h1a.5.5 0 01.5.5z" clip-rule="evenodd"/>
                    </svg>
                    <span class="tooltip">Mon compte</span>
                </a>
            </div>
        </form>
    </div>  
</div>