<div class="d-flex align-items-center justify-content-center myCards" id="customBg" style="background: url(<?= URL_SOURCES."/images/creative-light.jpg" ?>)">
    <div class="row">
        <div class="col-sm-12">
            <div class="card" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor']."d9" ?>; color: <?= $GLOBALS['STYLE']['textColor'] ?>;">
                <h2 class="text-center card-title mt-5" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">Mes données professionnelles</h2>
                <div class="row">
                    <div class="col">
                        <div class="card-body">
                            <div class="list-group">
                                <form method="POST" action="">
                                    <div class="form-group col-md-12">
                                        <label class="title2">Coaching Pratiqué</label>                                    
                                        <select class="browser-default custom-select" id="coachingDo" name="coachingDo">
                                            <option selected><?= $do = (empty($adminCoaching['coachingDo'])) ? 'Coaching Pratiqué' : $adminCoaching['coachingDo'] ?></option>
                                        <?php foreach($coach as $do): ?>
                                            <?php $do = substr($do, 1, -1); ?>
                                            <option value="<?= $do ?>"><?= $do ?></option>
                                        <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-12">
                                        <label class="title2">Adhérent</label>
                                        <select class="browser-default custom-select" id="adherent" name="adherent">
                                            <option selected><?= $ad = (empty($adminCoaching['adherent'])) ? 'Adhérent' : $adminCoaching['adherent'] ?></option>
                                        <?php foreach($adherent as $ad): ?>
                                            <?php $ad = substr($ad, 1, -1); ?>
                                            <option value="<?= $ad ?>"><?= $ad ?></option>
                                        <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-12">
                                    <label class="title2">Catégorie</label>
                                        <select class="browser-default custom-select" id="categorie" name="categorie">
                                            <option selected><?= $cat = (empty($adminCoaching['categorie'])) ? 'Catégorie' : $adminCoaching['categorie'] ?></option>
                                        <?php foreach($categorie as $cat): ?>
                                            <?php $cat = substr($cat, 1, -1); ?>
                                            <option value="<?= $cat ?>"><?= $cat ?></option>
                                        <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <div class="d-flex justify-content-end">
                                        <button type="submit" class="btn btn-warning mx-2 infobulle">
                                            <svg class="bi bi-upload text-white" width="2em" height="2em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd" d="M2.5 10a.5.5 0 01.5.5V14a1 1 0 001 1h12a1 1 0 001-1v-3.5a.5.5 0 011 0V14a2 2 0 01-2 2H4a2 2 0 01-2-2v-3.5a.5.5 0 01.5-.5zM7 6.854a.5.5 0 00.707 0L10 4.56l2.293 2.293A.5.5 0 1013 6.146L10.354 3.5a.5.5 0 00-.708 0L7 6.146a.5.5 0 000 .708z" clip-rule="evenodd"/>
                                                <path fill-rule="evenodd" d="M10 4a.5.5 0 01.5.5v8a.5.5 0 01-1 0v-8A.5.5 0 0110 4z" clip-rule="evenodd"/>
                                            </svg>
                                            <span class="tooltip">Envoyer</span>
                                        </button>
                                        <a href="<?= route_to_url('account') ?>" class="btn peach-gradient infobulle">
                                            <svg class="bi bi-house" width="2em" height="2em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd" d="M9.646 3.146a.5.5 0 01.708 0l6 6a.5.5 0 01.146.354v7a.5.5 0 01-.5.5h-4.5a.5.5 0 01-.5-.5v-4H9v4a.5.5 0 01-.5.5H4a.5.5 0 01-.5-.5v-7a.5.5 0 01.146-.354l6-6zM4.5 9.707V16H8v-4a.5.5 0 01.5-.5h3a.5.5 0 01.5.5v4h3.5V9.707l-5.5-5.5-5.5 5.5z" clip-rule="evenodd"/>
                                                <path fill-rule="evenodd" d="M15 4.5V8l-2-2V4.5a.5.5 0 01.5-.5h1a.5.5 0 01.5.5z" clip-rule="evenodd"/>
                                            </svg>
                                            <span class="tooltip">Mon compte</span>
                                        </a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>          
</div>