<div class="jumbotron jumbotron-fluid bg-Altair-grey text-white">
    <div class="row justify-content-center">
    <div class="card-grey p-3" style="box-shadow: <?= $GLOBALS['STYLE']['boxShadow'] ?>; background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] . 'd9' ?>; color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>;"> 
        <h3 class="mt-5">Ajouter ou modifier vos informations</h3>
        <form method="POST" action="" class="form">
            <div class="form-row my-5">
                <div class="form-group col-md-4">
                <select class="browser-default custom-select" id="inputRegion" name="region">
                    <option selected><?= $region = (empty($adminInfo['region'])) ? 'Région' : $adminInfo['region'] ?></option>
                <?php foreach($regions as $region): ?>
                    <option value="<?= $region ?>"><?= $region ?></option>
                    <?php endforeach; ?>
                </select>
                </div>
                <div class="form-group col-md-4">
                <select class="browser-default custom-select" id="inputDepartement" name="departement">
                    <option selected><?= $departement = (empty($adminInfo['departement'])) ? 'Département' : $adminInfo['departement'] ?></option>
                <?php foreach($dept as $key => $d): ?>
                    <option value="<?= $key . '  ' . $d ?>"><?= $key . '  ' . $d ?></option>
                <?php endforeach;?>
                </select>
                </div>
                <div class="form-group col-md-4">
                <input type="text" class="form-control" id="inputVille" placeholder="Ville" name="ville" value="<?= $ville = (empty($adminInfo['ville'])) ? '' : $adminInfo['ville'] ?>">
                </div>
                <div class="form-group col-md-12">
                <input type="text" class="form-control" id="inputAdresse" placeholder="Adresse" name="adresse" value="<?= $adresse = (empty($adminInfo['adresse'])) ? '' : $adminInfo['adresse'] ?>">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label for="inputSociety">Téléphone</label>
                    <input type="tel" class="form-control" id="inputPhone" pattern="[0-9]{2}[0-9]{2}[0-9]{2}[0-9]{2}[0-9]{2}" name="telephone" value="<?= $telephone = (empty($adminInfo['telephone'])) ? '' : $adminInfo['telephone'] ?>">
                </div>
                <div class="form-group col-md-3">
                    <label for="inputSociety">Profession</label>
                    <input type="text" class="form-control" id="inputjob" name="job" value="<?= $societe = (empty($adminInfo['job'])) ? '' : $adminInfo['job'] ?>">
                </div>
                <div class="form-group col-md-3">
                    <label for="inputSociety">Socièté</label>
                    <input type="text" class="form-control" id="inputSociety" name="societe" value="<?= $societe = (empty($adminInfo['societe'])) ? '' : $adminInfo['societe'] ?>">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputSociety">Site Web</label>
                    <input type="text" class="form-control" id="inputwebsite" name="website" value="<?= $website = (empty($adminInfo['website'])) ? '' : $adminInfo['website'] ?>">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label for="inputFacebook">Facebook</label>
                    <input type="url" class="form-control" id="inputFacebook" name="facebook" value="<?= $facebook = (empty($adminInfo['facebook'])) ? '' : $adminInfo['facebook'] ?>">
                </div>
                <div class="form-group col-md-3">
                    <label for="inputLinkedIn">LinkedIn</label>
                    <input type="url" class="form-control" id="inputLinkedIn" name="linkedin" value="<?= $linkedin = (empty($adminInfo['linkedin'])) ? '' : $adminInfo['linkedin'] ?>">
                </div>
                <div class="form-group col-md-3">
                    <label for="inputViadeo">Viadeo</label>
                    <input type="url" class="form-control" id="inputViadeo" name="viadeo" value="<?= $viadeo = (empty($adminInfo['viadeo'])) ? '' : $adminInfo['viadeo'] ?>">
                </div>            
                <div class="form-group col-md-3">
                    <label for="inputSkype">Skype</label>
                    <input type="text" class="form-control" id="inputSkype" name="skype" value="<?= $skype = (empty($adminInfo['skype'])) ? '' : $adminInfo['skype'] ?>">
                </div>
            </div>
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn elegant-color">Enregistrer / Modifier</button>
                <a href="<?= route_to_url('fullAccount') ?>?id=<?= $adminInfo['id_admin'] ?>" class="btn grey darken-1">
                    Mon compte
                </a>
            </div>
        </form>
    </div>
    </div>  
</div>