<div class="jumbotron jumbotron-fluid bg-Altair-grey text-white">
    <div class="row justify-content-center">
        <div class="card-grey p-3" style="box-shadow: <?= $GLOBALS['STYLE']['boxShadow'] ?>; background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] . 'd9' ?>; color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>;"> 
            <h3 class="mt-5">Ajouter ou modifier vos informations</h3>
            <form method="POST" action="" class="form">
                <div class="form-row mt-5">
                    <div class="form-group col-md-12">
                        <label for="inputintervention">Domaine d'intervention</label>
                        <input type="text" class="form-control" id="inputintervention" name="intervention" value="<?= (empty($admin['intervention'])) ? '' : $admin['intervention'] ?>">
                    </div>
                    <div class="form-group col-md-12">
                        <label for="inputtraining">Formation et certification</label>
                        <input type="text" class="form-control" id="inputtraining" placeholder="" name="training" value="<?= (empty($admin['training'])) ? '' : $admin['training'] ?>">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label for="inputSociety">Parcours</label>
                        <input type="text" class="form-control" id="inputcourse" name="course" value="<?= (empty($admin['course'])) ? '' : $admin['course'] ?>">
                    </div>
                    <div class="form-group col-md-12">
                        <label for="inputSociety">Publication</label>
                        <input type="text" class="form-control" id="inputpublication" name="publication" value="<?= (empty($admin['publication'])) ? '' : $admin['publication'] ?>">
                    </div>
                    <div class="form-group col-md-12">
                        <label for="inputSociety">Centre d'intérêt</label>
                        <input type="text" class="form-control" id="inputinterest" name="interest" value="<?= (empty($admin['interest'])) ? '' : $admin['interest'] ?>">
                    </div>
                    <div class="form-group col-md-12">
                        <label for="inputSociety">Citation</label>
                        <input type="text" class="form-control" id="inputquote" name="quote" value="<?= (empty($admin['quote'])) ? '' : $admin['quote'] ?>">
                    </div>
                </div>
                <div class="d-flex justify-content-end mt-5">
                    <button type="submit" class="btn elegant-color">Enregistrer / Modifier</button>
                    <a href="<?= route_to_url('fullAccount') ?>?id=<?= $admin['admin_id'] ?>" class="btn grey darken-1">
                        Mon compte
                    </a>
                </div>
            </form>
        </div>
    </div>  
</div>