<div class="jumbotron jumbotron-fluid bg-Altair-grey text-white">
    <div class="row justify-content-center p-4">
        <div class="card-grey p-3" style="box-shadow: <?= $GLOBALS['STYLE']['boxShadow'] ?>; background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] . 'd9' ?>; color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>;"> 
            <h3 class="mt-5">Ajouter ou modifier vos informations pro</h3>
            <form method="POST" action="" class="form">
                <div class="form-row mt-5">
                    <div class="form-group col-md-12">
                        <label class="title2">Coaching Pratiqué</label>                                    
                        <select class="browser-default custom-select" id="coachingDo" name="coachingDo" required>
                            <option value="<?= $adminCoaching['coachingDo'] ?>"><?= $do = (empty($adminCoaching['coachingDo'])) ? 'Coaching Pratiqué' : $adminCoaching['coachingDo'] ?></option>
                        <?php foreach($coach as $do): ?>
                            <?php $do = substr($do, 1, -1); ?>
                            <option value="<?= $do ?>"><?= $do ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="form-row my-2">
                    <div class="form-group col-md-12">
                        <label class="title2">Adhérent</label>
                        <select class="browser-default custom-select" id="adherent" name="adherent" required>
                            <option value=""><?= $ad = (empty($adminCoaching['adherent'])) ? 'Adhérent' : $adminCoaching['adherent'] ?></option>
                        <?php foreach($adherent as $ad): ?>
                            <?php $ad = substr($ad, 1, -1); ?>
                            <option value="<?= $ad ?>"><?= $ad ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="form-group col-md-12">
                        <label class="title2">Catégorie</label>
                        <select class="browser-default custom-select" id="categorie" name="categorie" required>
                            <option value=""><?= $cat = (empty($adminCoaching['categorie'])) ? 'Catégorie' : $adminCoaching['categorie'] ?></option>
                        <?php foreach($categorie as $cat): ?>
                            <?php $cat = substr($cat, 1, -1); ?>
                            <option value="<?= $cat ?>"><?= $cat ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label for="inputintervention">Domaine d'intervention</label>
                        <input type="text" class="form-control" id="inputintervention" name="intervention" value="<?= (empty($admin['intervention'])) ? '' : $admin['intervention'] ?>" required>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="inputtraining">Formation et certification</label>
                        <input type="text" class="form-control" id="inputtraining" placeholder="" name="training" value="<?= (empty($admin['training'])) ? '' : $admin['training'] ?>" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label for="inputSociety">Parcours</label>
                        <input type="text" class="form-control" id="inputcourse" name="course" value="<?= (empty($admin['course'])) ? '' : $admin['course'] ?>" required>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="inputSociety">Publication</label>
                        <input type="text" class="form-control" id="inputpublication" name="publication" value="<?= (empty($admin['publication'])) ? '' : $admin['publication'] ?>" required>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="inputSociety">Centre d'intérêt</label>
                        <input type="text" class="form-control" id="inputinterest" name="interest" value="<?= (empty($admin['interest'])) ? '' : $admin['interest'] ?>" required>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="inputSociety">Citation</label>
                        <input type="text" class="form-control" id="inputquote" name="quote" value="<?= (empty($admin['quote'])) ? '' : $admin['quote'] ?>" required>
                    </div>
                </div>
                <div class="d-flex justify-content-end mt-5">
                    <a href="<?= route_to_url('fullAccount') ?>?id=<?= $id ?>" class="btn grey darken-1">
                        Mon compte
                    </a>
                    <button type="submit" class="btn elegant-color">Enregistrer / Modifier</button>
                </div>
            </form>
        </div>
    </div>  
</div>