<div class="container-fluid d-flex align-items-center justify-content-center" style="background: url(<?= URL_SOURCES."/images/events/meeting.jpg"?>); filter: blur(.8); background-size: cover; background-position: center;">
    <div class="row my-5 w-100 justify-content-center">
    <?php foreach($allEvents as $event): ?>
        <?php $data = $event['start'];
                    $data = new DateTime($data);
                    $date = $data->format('Y/m/d');
                    setlocale(LC_TIME, "fr_FR", "French");
                    $date = strftime("%A %d %B %G", strtotime($date));
                    $event['date'] = ucwords($date); ?>
        <div class="col-md-4">
            <div class="card card-grey-3 bg-Altair-grey p-3 text-white my-5">
                <h3><i class="fas fa-circle fa-xs text-<?= $event['themeColor'] ?>"></i> <?= $event['date'] ?></h3>
                <h5 class="card-title ml-4">&nbsp;<?= $event['title'] ?></h5>
                <div class="card-body d-md-flex">
                    <button class="btn">
                        <a href="<?= route_to_url('currentEvent') ?>?id=<?= $event['id'] ?>">
                            <i class="fas fa-search-plus fa-lg"></i>&nbsp;Aperçu
                        </a>
                    </button>
                    <button class="btn elegant-color"><i class="fas fa-times fa-lg"></i>&nbsp;Refuser</button>
                    <form action="<?= route_to_url('evenements') ?>?id=<?= $event['id'] ?>" method="POST">
                        <input type="hidden" name=id value="<?= $event['id'] ?>">
                        <input type="hidden" name=isValide value="0">
                        <button class="btn btn-grey darken-1" type="submit">
                            <a href="">
                            </a>
                            <i class="fas fa-check fa-lg"></i>&nbsp;Accepter
                        </button>
                    </form>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>
