<div class="jumbotron jumbotron-fluid text-white bg-Altair-grey">
    <div class="container-fluid">
        <div class="row mb-5">
            <div class="col-sm-12 col-lg-6">
                <div class="card card-grey-2 p-4">
                    <div class="card-body" style="color: <?= $GLOBALS['STYLE']['textColor'] ?>;">
                        <h4 class="text-grey">INSTAGRAM</h4>
                        <p class="mt-5">
                            <label>Votre nouveau Token</label>
                            <input type="password" class="form-control" value="<?= (empty($result->access_token) ? '' : $result->access_token); ?>">
                        </p>
                        <p>
                            Expirera dans <span style="color: red"><?= (empty($dayTo->days) ? ' ' : $dayTo->days); ?></span> jours.
                        </p>
                        <div class="d-flex">
                            <form method="GET" action="">
                                <button type="submit" class="btn grey draken-1 mt-2" name="refresh">Renouvellement Token 60j</button>
                            </form>
                            <form action="" method="POST">
                                <input type="hidden" name="nextTokenDate" value="<?= (empty($nextDate))? '' : $nextDate ?>">
                                <input type="hidden" class="form-control" name="long_token_insta" value="<?= (empty($result->access_token) ? '' : $result->access_token); ?>">
                                <button type="submit" class="btn grey draken-1 mt-2" name="update">Mise a jour Base de Données et site</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-lg-6">
                <div class="card card-grey-2 p-4">
                    <div class="card-body">
                        <h4 class="text-grey">FACEBOOK</h4>
                            <a href="<?= htmlspecialchars($loginUrl) ?>" class="btn grey draken-1"> Se Connecter avec Facebook </a>
                    </div>
                </div>
            </div>
        </div>
    <!-- <div class="row">
        <div class="col-sm-12 col-lg-6">
            <div class="card bg-altairDark text-altairRose" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>">
                <div class="card-body">
                    <h4 class="text-center" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">VIMEO</h4>
                    
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-lg-6">
            <div class="card bg-altairDark text-altairRose" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>">
                <div class="card-body">
                    <h4 class="text-center" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">PINTEREST</h4>
                </div>
            </div>
        </div>
    </div>           -->
    </div>
</div>