<div class="container-fluid my-5">
    <div class="row mb-5">
        <div class="col-sm-12 col-lg-6">
            <div class="card bg-altairDark text-altairRose" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>">
                <div class="card-body" style="color: <?= $GLOBALS['STYLE']['textColor'] ?>;">
                    <h4 class="text-center" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">INSTAGRAM</h4>
                    <p>
                        <label>Votre nouveau Token</label>
                        <input type="password" class="form-control" value="<?= (empty($result->access_token) ? '' : $result->access_token); ?>">
                    </p>
                    <p>
                        Expirera dans <span style="color: red"><?= (empty($_SESSION['value']->days) ? ' ' : $_SESSION['value']->days); ?></span> jours.
                    </p>
                    <form method="GET" action="">
                        <button type="submit" class="btn btn-info mt-2" name="refresh">Token 60j</button>
                    </form>
                    <form action="" method="POST">
                        <input type="hidden" class="form-control" name="long_token_insta" value="<?= (empty($result->access_token) ? '' : $result->access_token); ?>">
                        <button type="submit" class="btn btn-info mt-2" name="update">Mise a jour</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-lg-6">
            <div class="card bg-altairDark text-altairRose" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>">
                <div class="card-body">
                    <h4 class="text-center" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">FACEBOOK</h4>
                    
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <div class="card bg-altairDark text-altairRose" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>">
                <div class="card-body">
                    <h4 class="text-center" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">VIMEO</h4>
                    
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-lg-6">
            <div class="card bg-altairDark text-altairRose" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>">
                <div class="card-body">
                    <h4 class="text-center" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">PINTEREST</h4>
                </div>
            </div>
        </div>
    </div>          
</div>