<div class="container-fluid my-5">
    <div class="row mb-5">
        <div class="col-sm-12 col-lg-6">
            <div class="card bg-altairDark text-altairRose" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>">
                <div class="card-body">
                    <h4 class="text-center" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">INSTAGRAM</h4>
                    <div class="row text-center mb-2">
                        <div class="col">
                            <label style="color: <?= $GLOBALS['STYLE']['textColor'] ?>;">App Id</label>
                            <input type="text" class="form-control" name="client_id">
                        </div>
                        <div class="col">
                            <label style="color: <?= $GLOBALS['STYLE']['textColor'] ?>;">App Secret</label>
                            <input type="text" class="form-control" name="">
                        </div>
                    </div>
                    <div class="row text-center mb-2">
                        <div class="col">
                            <label style="color: <?= $GLOBALS['STYLE']['textColor'] ?>;">Redirect Url</label>
                            <input type="text" class="form-control" name="redirect_uri">
                        </div>
                        <div class="col">
                            <label style="color: <?= $GLOBALS['STYLE']['textColor'] ?>;">Token</label>
                            <input type="text" class="form-control" name="token">
                        </div>
                    </div>
                    <div class="row text-center mb-2">
                        <div class="col">
                            <label style="color: <?= $GLOBALS['STYLE']['textColor'] ?>;">Long Token</label>
                            <input type="text" class="form-control" name="long_token">
                        </div>
                    </div>
                    <form method="POST" action="">
                        <div class="row text-center mb-2">
                            <div class="col">
                                <label style="color: <?= $GLOBALS['STYLE']['textColor'] ?>;">Code reçu</label>
                                <input type="text" name="code" class="form-control">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-info mt-2">Token 60j</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-lg-6">
            <div class="card bg-altairDark text-altairRose" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>">
                <div class="card-body">
                    <h4 class="text-center" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">FACEBOOK</h4>
                    
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <div class="card bg-altairDark text-altairRose" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>">
                <div class="card-body">
                    <h4 class="text-center" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">VIMEO</h4>
                    
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-lg-6">
            <div class="card bg-altairDark text-altairRose" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>">
                <div class="card-body">
                    <h4 class="text-center" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">PINTEREST</h4>
                </div>
            </div>
        </div>
    </div>          
</div>