<footer class="page-footer pt-4 myFooter" style="background-color: <?= $GLOBALS['STYLE']['backgroundColor'] ?>">
  <div class="footer-copyright text-center py-3" style="color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>;">
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
      © 2020 Copyright:
        <a href="#">LiSplib</a>
      </li>
      <li class="list-inline-item">
        <button type="button" class="btn-floating btn-lg btn-fb infobulle mr-2">
              <a href="https://www.facebook.com/AltairStrategieEtFormationEnCommunication" class="text-white"><i class="fab fa-facebook-f"></i></a>
              <span class="tooltip">Visualiser</span>
          </button>
       </li>
    </ul>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/js/mdb.min.js"></script>
<script>
    $(function () {
    $('[data-toggle="popover"]').popover()
    })
</script>