  <div class="footer-copyright text-center p-4" style="color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>;">
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        © 2020 Copyright:
        <a href="http://altair-communication.fr/">Altaïr Communication</a>
      </li>
      <li class="list-inline-item mx-2">
        <a href="#" data-container="body" data-toggle="popover" data-placement="bottom" data-content="06.33.26.19.57" class="text-white"><i class="fas fa-phone"></i></a>
      </li>
      <li class="list-inline-item mr-2">
          <a href="https://www.facebook.com/AltairStrategieEtFormationEnCommunication/posts/1609073655909754" class="text-white"><i class="fab fa-lg fa-facebook"></i></a>
       </li>
       <li class="list-inline-item">
          <a href="https://www.instagram.com/p/B_wio1hC6u_/" class="text-white"><i class="fab fa-lg fa-instagram"></i></a>
       </li>
    </ul>
  </div>
  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/js/mdb.min.js"></script>
<script>
    $(function () {
    $('[data-toggle="popover"]').popover()
    })
</script>
<script>
  $btnSidebar = document.getElementById('sidebarActive');
  $sidebar = document.getElementById('mySideBar')
  $btnSidebar.addEventListener('click', (e) => {
    $sidebar.classList.toggle('d-none')
  });
</script>