<nav class="navbar navbar-dark" style="background-color: <?= $GLOBALS['STYLE']['backgroundColor'] ?>; color: <?= $GLOBALS['STYLE']['textColor']?>">
    <?php if(isset($_SESSION['auth'])): ?>
        <a class="nav-item nav-link ml-auto text-white" href="<?= route_to_url('logout') ?>">
            <i class="fas fa-power-off"></i>
        </a>
        <?php else: ?>
            <div class="nav-item dropdown ml-auto">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
                    <i class="far fa-user"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-lg-right text-center" style="background-color: #1a1a1a; color: white;">
                    <form class="px-4 py-3" action="<?= route_to_url('connect')?>" method="POST">
                        <div class="form-group">
                            <label for="exampleDropdownFormEmail1">Email</label>
                            <input type="email" class="form-control" id="exampleDropdownFormEmail1" name="email">
                        </div>
                        <div class="form-group">
                            <label for="exampleDropdownFormPassword1">Mot de passe</label>
                            <input type="password" class="form-control" id="exampleDropdownFormPassword1" name="password">
                        </div>
                        <button type="submit" class="btn btn-info">Se Connecter</button>
                    </form>
                </div>
            </div>
    <?php endif; ?>
    <button id="sidebarActive" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
</nav>
<nav class="d-none sidebar bg-dark navbar-dark" id="mySideBar">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav ml-5 mt-5">
            <a class="nav-link" href="<?= route_to_url('calendar') ?>">
                Calendrier Évènements
            </a>
        <?php if(isset($_SESSION['auth'])): ?>
            <a class="nav-item nav-link" href="<?= route_to_url('logout') ?>">
                Se déconnecter
            </a>
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Mon Compte
                </a>
                <div class="dropdown-menu" style="background-color: <?= $GLOBALS['STYLE']['backgroundColor'] ?>; color: <?= $GLOBALS['STYLE']['textColor'] ?>;" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="<?= route_to_url('account') ?>">Mon compte</a>
                    <?php if ($_SESSION['auth']['role'] === 'superAdmin'): ?>
                        <a class="dropdown-item" href="<?= route_to_url('parameter') ?>">Paramètrage</a>
                        <a class="dropdown-item" href="<?= route_to_url('socialMedia') ?>">Réseaux Sociaux</a>
                        <a href="<?= route_to_url('imageResize') ?>" class="dropdown-item">Resizer</a>
                    <?php endif; ?>
                    <a class="dropdown-item" href="<?= route_to_url('myEvents') ?>">Mes évènements</a>
                    <?php if ($_SESSION['auth']['role'] === 'superAdmin'): ?>
                        <?php foreach($GLOBALS['await'] as $await) : ?>
                            <?php if($await > 0) : ?>
                                <a class="dropdown-item" href="<?= route_to_url('evenements')?>">Évènements à valider <span class="badge badge-warning"> <?= $await ?> </span></a>
                            <?php else : ?>
                                <a class="dropdown-item" href="<?= route_to_url('evenements')?>">Évènements à valider</a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        <?php foreach($GLOBALS['new'] as $GLOBALS['n']): ?>
                            <?php if($GLOBALS['n'] > 0) : ?>
                                <a class="dropdown-item" href="<?= route_to_url('members') ?>" title="Coach en attente">Liste des Membres <span class="badge badge-warning"> <?= $GLOBALS['n'] ?> </span></a>
                            <?php else : ?>
                                <a class="dropdown-item" href="<?= route_to_url('members') ?>" title="Coach en attente">Liste des Membres</a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
        <?php else: ?>
            <a class="nav-item nav-link" href="<?= route_to_url('register') ?>">
                S'inscrire
            </a>
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
                    Se Connecter
                </a>
                <div class="dropdown-menu text-center" style="background-color: #1a1a1ad9; color: white;">
                    <form class="px-4 py-3" action="<?= route_to_url('connect')?>" method="POST">
                        <div class="form-group">
                            <label for="exampleDropdownFormEmail1">Email</label>
                            <input type="email" class="form-control" id="exampleDropdownFormEmail1" name="email">
                        </div>
                        <div class="form-group">
                            <label for="exampleDropdownFormPassword1">Mot de passe</label>
                            <input type="password" class="form-control" id="exampleDropdownFormPassword1" name="password">
                        </div>
                        <button type="submit" class="btn btn-info">Se Connecter</button>
                    </form>
                </div>
            </div>
        <?php endif; ?>
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownFb" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Facebook
                        <?php if(!empty($_SESSION['alert'])) : ?>
                            <?php if(isset($_SESSION['alert'])) : ?>
                                <?php foreach($_SESSION['alert'] as $type => $message): ?>
                                    <span class="badge badge-<?= $type ?>">
                                        <?= $message; ?>
                                    </span>
                                <?php endforeach; ?>
                            <?php unset($_SESSION['alert']); ?>
                            <?php endif; ?>
                        <?php endif; ?>
                </a>
                <div class="dropdown-menu" style="background-color: <?= $GLOBALS['STYLE']['backgroundColor'] ?>; color: <?= $GLOBALS['STYLE']['textColor'] ?>;" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="https://www.facebook.com/AltairStrategieEtFormationEnCommunication">
                    Facebook
                    </a>
                    <a class="dropdown-item" href="<?= route_to_url('facebook') ?>">
                        Nos Évènements
                    </a>
                    <a class="dropdown-item" href="<?= route_to_url('facebookLive') ?>">
                        Live Facebook
                    </a>
                </div>
            </div>
                <a class="nav-link" href="<?= route_to_url('instagram') ?>">
                        Instagram
                </a>
                <a class="nav-link" href="https://vimeo.com/agencealtair">
                        Vimeo
                </a>
                <a class="nav-link" href="https://www.pinterest.fr/altaircommunication/">
                        Pinterest
                </a>
            </div>
        <?php if(isset($_SESSION['auth'])): ?>
            <div class="nav-item dropdown ml-5">
                <form class="form-inline md-form" action="<?= route_to_url('search') ?>">
                    <input class="form-control mr-sm-2" type="search" placeholder="Rechercher" name="search_name" aria-label="Search">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownSearch" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                    <div class="dropdown-menu text-center dropdown-menu-lg-right" style="background-color: inherit;">
                        <select class="browser-default custom-select" name="filter" id="filter">
                            <option value="" disabled selected>Coaching pratiqué</option>
                            <option value="coachPro">coach professionnel de la personne</option>
                            <option value="equipeOrganisation">coach professionnel d’équipe et d’organisation</option>
                            <option value="animateur">animateur co-développement professionnel</option>
                            <option value="talent">coach professionnel certifié «Talent»</option>
                            <option value="superviseur">coach professionnel superviseur</option>
                        </select>
                    </div>
                    <div class="dropdown-menu text-center dropdown-menu-lg-right" style="background-color: inherit;">
                        <select class="browser-default custom-select" name="coachingType" id="coachingType">
                            <option value="" disabled selected>Type Coaching</option>
                            <option value="dirigeant">coaching de dirigeant</option>
                            <option value="grandeEntreprise">coaching de grandes entreprises</option>
                            <option value="pme">coaching de PME</option>
                        </select>
                    </div>
                    <button class="btn btn-info my-2 my-sm-0" type="submit" name="form_submit">
                        <i class="fas fa-search fa-lg"></i>
                    </button>
                </form>
            </div>
        <?php endif; ?>
    </div>
</nav>
<?php if(!empty($_SESSION['flash'])) : ?>
<div class="container text-center mt-4">
    <?php if(isset($_SESSION['flash'])): ?>
        <?php foreach($_SESSION['flash'] as $type => $message): ?>
            <div class="alert alert-<?= $type; ?>">
                <?= $message; ?>
            </div>
        <?php endforeach; ?>
        <?php unset($_SESSION['flash']); ?>
    <?php endif; ?>
</div>
<?php endif; ?>