<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Formation Coaching</title>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/css/mdb.min.css" rel="stylesheet">
        <link rel="stylesheet" href="<?= URL_SOURCES."/css/style.css" ?>">
    </head>
    <body>
        <header>
            <?php include 'header.phtml'; ?>
        </header>
        <main>
            <?php (!empty($_SESSION['auth']) ? include $app['view'] : include 'add/addAdmin.phtml'); ?>
        </main>
        <footer class="footer mt-auto py-3 myFooter" style="background-color: <?= $GLOBALS['STYLE']['backgroundColor'] ?>">
            <?php include 'footer.phtml'; ?>
        </footer>
    </body>
</html>