<div class="jumbotron jumbotron-fluid bg-Altair-grey text-white" style="background: url('<?= URL_SOURCES ?>/images/register.jpg');">
    <div class="container mt-5">    
        <form action="<?= route_to_url('register') ?>" method="POST" class="p-4 card-grey-2">
            <h1 class="text-grey">Enregistrez-vous</h1>
            <div class="form-row justify-content-center">    
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="customSwitch1" name="coach">
                    <label class="custom-control-label" for="customSwitch1">S'inscrire comme Coach</label>
                </div>
            </div>
            <div class="form-row justify-content-center">    
                <div class="form-group col-md-4">
                    <label for="lastname">Nom</label>
                    <input type="text" name="lastname" class="form-control" value="<?= isset($data['lastname']) ? htmlentities($data['lastname']) : '' ?>">
                        <?php if (isset($errors['lastname'])): ?>
                            <p class="form-text px-4 text-danger"><?= $errors['lastname']; ?></p>
                        <?php endif; ?>
                </div>
            </div>
            <div class="form-row justify-content-center">    
                <div class="form-group col-md-4">
                    <label for="firstname">Prénom</label>
                    <input type="text" name="firstname" class="form-control" value="<?= isset($data['firstname']) ? htmlentities($data['firstname']) : '' ?>">
                        <?php if (isset($errors['firstname'])): ?>
                            <p class="form-text px-4 text-danger"><?= $errors['firstname']; ?></p>
                        <?php endif; ?>
                </div>
            </div>
            <div class="form-row justify-content-center">
                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="email" name="email" class="form-control" value="<?= isset($data['email']) ? htmlentities($data['email']) : '' ?>">
                        <?php if (isset($errors['email'])): ?>
                            <p class="form-text px-4 text-danger"><?= $errors['email']; ?></p>
                        <?php endif; ?>
                        <?php if (isset($errors['emailExist'])): ?>
                            <p class="form-text px-4 text-danger"><?= $errors['emailExist']; ?></p>
                        <?php endif; ?>
                </div>
            </div>
            <div class="form-row justify-content-center">
                <div class="form-group col-md-4">
                    <label for="image">Photo de profil</label>
                    <input type="url" name="image" class="form-control" value="<?= isset($data['image']) ? htmlentities($data['image']) : '' ?>" placeholder="url d'une image déjà hébergée">
                        <?php if (isset($errors['image'])): ?>
                            <p class="form-text px-4 text-danger"><?= $errors['image']; ?></p>
                        <?php endif; ?>
                </div>
            </div>
            <div class="form-row justify-content-center">    
                <div class="form-group col-md-4">
                    <label for="password">Mot de passe</label>
                    <input type="password" name="password" class="form-control">
                        <?php if (isset($errors['password'])): ?>
                            <p class="form-text px-4 text-danger"><?= $errors['password']; ?></p>
                        <?php endif; ?>
                </div>
            </div>
            <div class="form-row justify-content-center">    
                <div class="form-group col-sm-10 col-md-4">
                    <label for="confirm_password">Confirmez le mot de passe</label>
                    <input type="password" name="confirm_password" class="form-control">
                </div>
            </div>
            <div>
                <div class="row justify-content-center">
                    <button type="submit" value="Connect" class="btn btn-grey darken-1">S'enregistrer</button>
                </div>
            </div>
        </form>
    </div>
</div>