<div class="jumbotron jumbotron-fluid text-center" style="opacity: 1!important; background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>; background: url(<?= URL_SOURCES."/images/events/block-chain.jpg"?>); background-size: 100% 100%">
    <div class="container mt-5">    
        <form action="<?= route_to_url('register') ?>" method="POST" class="py-3" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor']."d9" ?>; color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>;">
            <h1 style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">ENREGISTREZ-VOUS</h1>
            <div class="form-row justify-content-center">    
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="customSwitch1" name="coach">
                    <label class="custom-control-label" for="customSwitch1">S'inscrire comme Coach</label>
                </div>
            </div>
            <div class="form-row justify-content-center">    
                <div class="form-group col-md-4">
                    <label for="">Nom</label>
                    <input type="text" name="lastname" class="form-control"/>
                </div>
            </div>
            <div class="form-row justify-content-center">    
                <div class="form-group col-md-4">
                    <label for="">Prénom</label>
                    <input type="text" name="firstname" class="form-control"/>
                </div>
            </div>
            <div class="form-row justify-content-center">
                <div class="form-group col-md-4">
                    <label for="">Email</label>
                    <input type="email" name="email" class="form-control"/>
                </div>
            </div>
            <div class="form-row justify-content-center">
                <div class="form-group col-md-4">
                    <label for="">Photo de profil</label>
                    <input type="url" name="image" class="form-control" placeholder="url d'une image déjà hébergée"/>
                </div>
            </div>
            <div class="form-row justify-content-center">    
                <div class="form-group col-md-4">
                        <label>Mot de passe</label>
                        <input type="password" name="password" class="form-control"/>
                </div>
            </div>
            <div class="form-row justify-content-center">    
                <div class="form-group col-sm-10 col-md-4">
                    <label for="">Confirmez le mot de passe</label>
                    <input type="password" name="confirm_password" class="form-control"/>
                </div>
            </div>
            <div>
                <button type="submit" value="Connect" class="btn btn-info">S'enregistrer</button>
            </div>
        </form>
    </div>
</div>