<div class="jumbotron jumbotron-fluid bg-Altair-grey text-white">
    <div class="container mt-5">    
        <form action="<?= route_to_url('register') ?>" method="POST" class="p-4 card-grey-2">
            <h1 class="text-grey">Enregistrez-vous</h1>
            <div class="form-row justify-content-center">    
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="customSwitch1" name="coach">
                    <label class="custom-control-label" for="customSwitch1">S'inscrire comme Coach</label>
                </div>
            </div>
            <div class="form-row justify-content-center">    
                <div class="form-group col-md-4">
                    <label for="">Nom</label>
                    <input type="text" name="lastname" class="form-control"/>
                </div>
            </div>
            <div class="form-row justify-content-center">    
                <div class="form-group col-md-4">
                    <label for="">Prénom</label>
                    <input type="text" name="firstname" class="form-control"/>
                </div>
            </div>
            <div class="form-row justify-content-center">
                <div class="form-group col-md-4">
                    <label for="">Email</label>
                    <input type="email" name="email" class="form-control"/>
                </div>
            </div>
            <div class="form-row justify-content-center">
                <div class="form-group col-md-4">
                    <label for="">Photo de profil</label>
                    <input type="url" name="image" class="form-control" placeholder="url d'une image déjà hébergée"/>
                </div>
            </div>
            <div class="form-row justify-content-center">    
                <div class="form-group col-md-4">
                        <label>Mot de passe</label>
                        <input type="password" name="password" class="form-control"/>
                </div>
            </div>
            <div class="form-row justify-content-center">    
                <div class="form-group col-sm-10 col-md-4">
                    <label for="">Confirmez le mot de passe</label>
                    <input type="password" name="confirm_password" class="form-control"/>
                </div>
            </div>
            <div>
                <div class="row justify-content-center">
                    <button type="submit" value="Connect" class="btn btn-grey darken-1">S'enregistrer</button>
                </div>
            </div>
        </form>
    </div>
</div>