<?php
if (!empty($errors)): ?>
    <div class="container text-center">
        <div class="alert alert-danger">
            Merci de corriger vos erreurs
        </div>
    </div>
<?php endif; ?>
<div class="container-fluid text-center d-flex align-items-center justify-content-center myCards" style="background: url(<?= URL_SOURCES.'/images/events/board-4887880_1920.jpg' ?>); background-size: 100% auto; background-position: center;">
    <div class="row">
        <div class="col-12">
            <div class="card p-3" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor']."f5" ?>; color: white; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>;">
                <h1 style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;" class="card-title mt-2">Créer un événemment</h1>
                <div class="card-body">
                    <form method="POST" action="">
                        <div class="row my-2">    
                            <div class="col-12">
                                <input type="text" class="form-control bg-dark" id="title" name="title" required value="<?= isset($data['title']) ? htmlentities($data['title']) : '' ?>" placeholder="Titre de l'événement">
                                <?php if (isset($errors['title'])): ?>
                                    <small class="form-text text-muted"><?= $errors['title']; ?></small>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="row my-2">
                            <div class="col">
                                <input type="url" name="urlImage" class="form-control bg-dark" id="urlImage" value="<?= isset($data['urlImage']) ? htmlentities($data['urlImage']) : '' ?>" placeholder="url d'une image déjà en ligne">
                            </div>
                        </div>
                        <div class="row my-2">
                            <div class="col">
                                <select class="browser-default custom-select bg-dark" id="theme" name="theme">
                                    <option selected><?= $t = isset($data['theme']) ? htmlentities($data['theme']) : 'Thème' ?></option>
                                    <?php foreach($theme as $t): ?>
                                        <?php $t = substr($t, 1, -1); ?>
                                        <option value="<?= $t ?>"><?= $t ?></option>
                                    <?php endforeach; ?>
                                    <?php if (isset($errors['theme'])): ?>
                                        <small class="form-text text-muted"><?= $errors['theme']; ?></small>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div>
                        <div class="row my-2">
                            <div class="col">
                                <input type="date" class="form-control bg-dark" id="date" name="date" required value="<?= isset($data['date']) ? htmlentities($data['date']) : '' ?>">
                                <?php if (isset($errors['date'])): ?>
                                    <small class="form-text text-muted"><?= $errors['date']; ?></small>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="row my-2">
                            <div class="col-6">
                                <input type="time" class="form-control bg-dark" id="start" name="start" placeholder="HH:MM" required value="<?= isset($data['start']) ? htmlentities($data['start']) : '' ?>">
                                <?php if (isset($errors['start'])): ?>
                                    <small class="form-text text-muted"><?= $errors['start']; ?></small>
                                <?php endif; ?>
                            </div>
                            <div class="col-6">
                                <input type="time" class="form-control bg-dark" id="end" name="end" placeholder="HH:MM" required value="<?= isset($data['end']) ? htmlentities($data['end']) : '' ?>">
                            </div>
                        </div>
                        <div class="row my-2">
                            <div class="col">
                                <textarea name="content" class="form-control bg-dark" id="content" placeholder="Description"><?= isset($data['content']) ? htmlentities($data['content']) : '' ?></textarea>
                            </div>
                        </div>
                        <div class="row my-2">
                            <div class="col">
                                <input type="text" class="form-control bg-dark" id="adress" name="adress" placeholder="Adresse" required value="<?= isset($data['adress']) ? htmlentities($data['adress']) : '' ?>">
                            </div>
                        </div>
                        <div class="row my-2">
                            <div class="col-6">
                                <input type="text" class="form-control bg-dark" id="zipcode" name="zipcode" placeholder="Code Postal" required value="<?= isset($data['zipcode']) ? htmlentities($data['zipcode']) : '' ?>">
                            </div>
                            <div class="col-6">
                                <input type="text" class="form-control bg-dark" id="city" name="city" placeholder="Ville" required value="<?= isset($data['city']) ? htmlentities($data['city']) : '' ?>">
                            </div>
                        </div>
                        <button class="btn elegant-color">
                            <a href="<?= route_to_url('calendar') ?>">
                                <i class="fas fa-times fa-lg"></i>&nbsp;Annuler
                            </a>
                        </button>
                        <button type="submit" class="btn btn-grey darken-1">
                            <i class="fas fa-check fa-lg"></i>&nbsp;Enregistrer
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>