<?php
if (!empty($errors)): ?>
    <div class="container text-center">
        <div class="alert alert-danger">
            Merci de corriger vos erreurs
        </div>
    </div>
<?php endif; ?>

<div class="container-fluid text-center d-flex align-items-center justify-content-center bg-grey myCards">
    <div class="row">
        <div class="col-12">
            <div class="card p-3 bg-grey card-grey-2">
                <h2 class="card-title mt-2 text-grey text-left ml-4">Créer un événemment</h2>
                <div class="card-body">
                    <form method="POST" action="">
                        <div class="row my-3">    
                            <div class="col-12">
                                <input type="text" class="form-control bg-dark" id="title" name="title" value="<?= isset($data['title']) ? htmlentities($data['title']) : '' ?>" placeholder="Titre de l'événement" required>
                                <?php if (isset($errors['title'])): ?>
                                    <small class="form-text text-muted"><?= $errors['title']; ?></small>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="row my-3">
                            <div class="col">
                                <input type="url" name="urlImage" class="form-control" id="urlImage" value="<?= isset($data['urlImage']) ? htmlentities($data['urlImage']) : '' ?>" placeholder="url d'une image déjà en ligne">
                            </div>
                        </div>
                        <div class="row my-3">
                            <div class="col">
                                <select class="browser-default custom-select" id="theme" name="theme" required>
                                    <option value=""><?= $t = isset($data['theme']) ? htmlentities($data['theme']) : 'Thème' ?></option>
                                    <?php foreach($theme as $t): ?>
                                        <?php $t = substr($t, 1, -1); ?>
                                        <option value="<?= $t ?>"><?= $t ?></option>
                                    <?php endforeach; ?>
                                    <?php if (isset($errors['theme'])): ?>
                                        <small class="form-text text-muted"><?= $errors['theme']; ?></small>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div>
                        <div class="row my-3">
                            <div class="col">
                                <input type="date" class="form-control bg-dark" id="date" name="date" value="<?= isset($data['date']) ? htmlentities($data['date']) : '' ?>" required>
                                <?php if (isset($errors['date'])): ?>
                                    <small class="form-text text-muted"><?= $errors['date']; ?></small>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="row my-3">
                            <div class="col-6">
                                <input type="time" class="form-control bg-dark" id="start" name="start" placeholder="HH:MM" value="<?= isset($data['start']) ? htmlentities($data['start']) : '' ?>" required>
                                <?php if (isset($errors['start'])): ?>
                                    <small class="form-text text-muted"><?= $errors['start']; ?></small>
                                <?php endif; ?>
                            </div>
                            <div class="col-6">
                                <input type="time" class="form-control bg-dark" id="end" name="end" placeholder="HH:MM" value="<?= isset($data['end']) ? htmlentities($data['end']) : '' ?>" required>
                            </div>
                        </div>
                        <div class="row my-3">
                            <div class="col">
                                <textarea name="content" class="form-control bg-dark" id="content" placeholder="Description"><?= isset($data['content']) ? htmlentities($data['content']) : '' ?></textarea>
                            </div>
                        </div>
                        <div class="row my-3">
                            <div class="col">
                                <input type="text" class="form-control bg-dark" id="adress" name="adress" placeholder="Adresse" value="<?= isset($data['adress']) ? htmlentities($data['adress']) : '' ?>" required>
                            </div>
                        </div>
                        <div class="row my-3">
                            <div class="col-6">
                                <input type="text" class="form-control bg-dark" id="zipcode" name="zipcode" placeholder="Code Postal" pattern="^(2[A|B])|[0-9]{2}[0-9]{3}" value="<?= isset($data['zipcode']) ? htmlentities($data['zipcode']) : '' ?>" required>
                            </div>
                            <div class="col-6">
                                <input type="text" class="form-control bg-dark" id="city" name="city" placeholder="Ville" value="<?= isset($data['city']) ? htmlentities($data['city']) : '' ?>" required>
                            </div>
                        </div>
                        <div class="row" style="padding-right: 10px; padding-left: 10px;">
                            <button class="btn elegant-color flex-grow-1">
                                <a href="<?= route_to_url('calendar') ?>">
                                    <i class="fas fa-times fa-lg"></i>&nbsp;Annuler
                                </a>
                            </button>
                            <button type="submit" class="btn btn-grey darken-1 flex-grow-1">
                                <i class="fas fa-check fa-lg"></i>&nbsp;Enregistrer
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>