<div class="container-fluid d-flex align-items-center justify-content-center" style="background: url(<?= URL_SOURCES."/images/events/meeting.jpg"?>); filter: blur(.8); color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>; background-size: cover; background-position: center;">
    <div class="card p-3 my-5" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor']."d9" ?>;">
        <div class="row mb-3">
            <div class="col-md-6">
                <div class="card bg-dark p-3 cardEvent">
                    <h3><i class="fas fa-circle fa-xs text-<?= $event->getThemeColor() ?>"></i> <?= $date; ?></h3>
                    <h3 class="card-title">
                        <?= htmlentities(ucwords($event->getTitle())); ?>
                    </h3>
                    <h5 class="card-title"><i class="far fa-compass"></i><?= $event->getAdress()?>&nbsp;<?= $event->getZipcode() ?>&nbsp;<?= $event->getCity() ?></h5>
                    <?php if($event->getIsValide() === '1'): ?>
                    <p class="text-danger">En attente de validation</p>
                    <?php endif; ?>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card bg-dark p-3 cardEvent">
                    <img src="<?= $event->getUrlImage(); ?>" alt="<?= $event->getTitle() ?>" class="img-fluid" style="height: 123.2px;">
                </div>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-12 text-center">
            <?php $currentDate = new DateTime(); ?>
                <?php if ($currentDate < $event->getStart() && $event->getId_admin() !== $_SESSION['auth']['id']): ?>
                    <button type="button" class="btn" data-toggle="modal" data-target="#exampleModal">
                        <i class="far fa-heart fa-3x"></i>
                        <span>Je participe</span>
                    </button>
                    <button type="button" class="btn" data-toggle="modal" data-target="#exampleModal2">
                        <i class="far fa-smile-wink fa-3x"></i>
                        <span>Je suis intéressé(e)</span>
                    </button>
                    <button type="button" class="btn" data-toggle="modal" data-target="#exampleModal2">
                        <i class="fas fa-share-alt fa-3x"></i>
                        <span>Partager</span>
                    </button>
                <?php endif; ?>
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content"  style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>; color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>;">
                            <div class="modal-header justify-content-center">
                                <h5 class="modal-title" id="exampleModalLabel" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">
                                    S'inscrire à l'évènement
                                </h5>
                            </div>
                            <div class="modal-body">
                                <form action="" method="POST">
                                    <div class="form-row justify-content-center">    
                                        <div class="form-group col-md-4">
                                            <input class="form-control text-center" type="text" name="eventId" placeholder="<?= $event->getTitle(); ?>" readonly>
                                        </div>
                                    </div>
                                    <div class="form-row justify-content-center">    
                                        <div class="form-group col-md-4">
                                            <input class="form-control text-center" type="text" name="eventId" placeholder="<?= $event->getStart()->format('d-m-Y'); ?>" readonly>
                                        </div>
                                    </div>
                                    <div class="form-row justify-content-center">    
                                        <div class="form-group col-md-4">
                                            <input class="form-control text-center" type="text" name="userId" placeholder="<?= $_SESSION['username'] ?>" readonly>
                                        </div>
                                    </div>
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Annuler</button>
                                    <button type="submit" class="btn btn-info">Je participe</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card bg-dark p-3 cardEvent">
                        <h5 class=" text-<?= $event->getThemeColor() ?>"><?= $event->getTheme() ?></h5>
                        <p><?= htmlentities($event->getContent()); ?></p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Incidunt cum consequatur reprehenderit iste. Nobis placeat tempore corporis reiciendis illo at, quis saepe recusandae nulla nihil, sapiente quod voluptatem praesentium aliquid?</p>
                </div>
            </div>
        </div>
        <div class="row p-3">
            <div class="col-md-6">
                <h5 class="mt-3"><i class="far fa-user"></i> Créateur de l'évènement</h5>
                <img src="<?= $event->getImage(); ?>" style="border-radius: 10px; width: 50px;" class="card-img">
                <span class="mt-3"><?= $event->getLastname(); ?></span>&ensp;<span class="mt-3"><?= $event->getFirstname() ?></span>
            </div>
            <div class="col-md-6">
                <h5 class="mt-3"><i class="far fa-clock"></i> Horaires</h5>
                <span><?= $event->getStart()->format('H'); ?>h<?= $event->getStart()->format('i') ?> - <?= $event->getEnd()->format('H'); ?>h<?= $event->getEnd()->format('i'); ?></span>
            </div>
        </div>
        <div class="row p-3">            
            <div class="col-md-6">
                <?php foreach ($participants as $participant): ?>
                    <h5 class="mt-3"><i class="far fa-heart"></i> <?= $participant; ?> - Participants inscrits</h5>
                    <?php foreach ($register as $reg): ?>
                        <img style="width:50px; border-radius: 10px;" src="<?= $reg['image'] ?>" class="ml-3">
                        <span><?= $reg['lastname'] ?>&nbsp;<?= $reg['firstname'] ?></span>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </div>
            <div class="col-md-6">
                <?php foreach ($participants as $participant): ?>
                    <h5 class="mt-3"><i class="far fa-smile-wink"></i> <?= $participant; ?> - Participants intéressés</h5>
                    <?php foreach ($register as $reg): ?>
                        <img style="width:50px; border-radius: 10px;" src="<?= $reg['image'] ?>" class="ml-3">
                        <span><?= $reg['lastname'] ?>&nbsp;<?= $reg['firstname'] ?></span>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </div>
        </div>
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item imgMap" src="<?= $maps ?>" allowfullscreen></iframe>
            </div>
    </div>
</div>