<?php 
$currentDate = new DateTime();
?>
<div class="container-fluid text-center d-flex align-items-center justify-content-center myCards" style="background: url(<?= URL_SOURCES."/images/events/meeting.jpg"?>); filter: blur(.8); color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>; background-size: cover; background-position: center;">
    <div class="card p-3 my-5" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor']."d9" ?>;">
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="<?= $event->getImage(); ?>" style="border-radius: 50%;" class="card-img">
                <h5 class="mt-3"><?= $event->getLastname(); ?></h5>
            </div>
            <div class="col-md-6">
            <h1 style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;"><?= htmlentities($event->getTitle()); ?></h1>
                <div class="card-body">
                    <h5 class="card-title">
                        Date: <?= $event->getStart()->format('d/m/Y'); ?>
                    </h5>
                    <h6 class="card-subtitle mb-2">
                        Heure de début: <?= $event->getStart()->format('H:i'); ?> - Heure de fin: <?= $event->getEnd()->format('H:i'); ?>
                    </h6>
                    <p><?= htmlentities($event->getContent()); ?></p>
                    <a href="<?= route_to_url('calendar') ?>" class="btn peach-gradient mt-2 infobulle">
                        <svg class="bi bi-house" width="2em" height="2em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M9.646 3.146a.5.5 0 01.708 0l6 6a.5.5 0 01.146.354v7a.5.5 0 01-.5.5h-4.5a.5.5 0 01-.5-.5v-4H9v4a.5.5 0 01-.5.5H4a.5.5 0 01-.5-.5v-7a.5.5 0 01.146-.354l6-6zM4.5 9.707V16H8v-4a.5.5 0 01.5-.5h3a.5.5 0 01.5.5v4h3.5V9.707l-5.5-5.5-5.5 5.5z" clip-rule="evenodd"></path>
                            <path fill-rule="evenodd" d="M15 4.5V8l-2-2V4.5a.5.5 0 01.5-.5h1a.5.5 0 01.5.5z" clip-rule="evenodd"></path>
                        </svg>
                        <span class="tooltip">Accueil</span>
                    </a>
                    <?php if ($currentDate < $event->getStart()): ?>
                    <button type="button" class="btn btn-success mt-2" data-toggle="modal" data-target="#exampleModal">
                        <svg aria-hidden="true" focusable="false" width="2em" height="2em" data-prefix="far" data-icon="calendar-check" class="svg-inline--fa fa-calendar-check fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M400 64h-48V12c0-6.627-5.373-12-12-12h-40c-6.627 0-12 5.373-12 12v52H160V12c0-6.627-5.373-12-12-12h-40c-6.627 0-12 5.373-12 12v52H48C21.49 64 0 85.49 0 112v352c0 26.51 21.49 48 48 48h352c26.51 0 48-21.49 48-48V112c0-26.51-21.49-48-48-48zm-6 400H54a6 6 0 0 1-6-6V160h352v298a6 6 0 0 1-6 6zm-52.849-200.65L198.842 404.519c-4.705 4.667-12.303 4.637-16.971-.068l-75.091-75.699c-4.667-4.705-4.637-12.303.068-16.971l22.719-22.536c4.705-4.667 12.303-4.637 16.97.069l44.104 44.461 111.072-110.181c4.705-4.667 12.303-4.637 16.971.068l22.536 22.718c4.667 4.705 4.636 12.303-.069 16.97z"></path></svg>
                    </button>
                    <?php endif; ?>
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content"  style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>; color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>;">
                                <div class="modal-header justify-content-center">
                                    <h5 class="modal-title" id="exampleModalLabel" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">
                                        S'inscrire à l'évènement
                                    </h5>
                                </div>
                                <div class="modal-body">
                                    <form action="" method="POST">
                                        <div class="form-row justify-content-center">    
                                            <div class="form-group col-md-4">
                                                <input class="form-control text-center" type="text" name="eventId" placeholder="<?= $event->getTitle(); ?>" readonly>
                                            </div>
                                        </div>
                                        <div class="form-row justify-content-center">    
                                            <div class="form-group col-md-4">
                                                <input class="form-control text-center" type="text" name="eventId" placeholder="<?= $event->getStart()->format('d-m-Y'); ?>" readonly>
                                            </div>
                                        </div>
                                        <div class="form-row justify-content-center">    
                                            <div class="form-group col-md-4">
                                                <input class="form-control text-center" type="text" name="userId" placeholder="<?= $_SESSION['username'] ?>" readonly>
                                            </div>
                                        </div>
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Annuler</button>
                                        <button type="submit" class="btn btn-info">S'inscrire</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <?php foreach ($participants as $participant): ?>
                    <h5>Nombre de participant inscrit: <?= $participant; ?></h5>
                    <?php foreach ($register as $reg): ?>
                        <img style="width:50px;" src="<?= $reg['image'] ?>" title="<?= $reg['lastname'] ?>">
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>