<div class="container text-center text-white bg-dark my-5">
    <div class="row">
        <div class="col-sm-12">
            <div class="card bg-dark text-white text-center mt-5">
                <h1 class="card-title mt-2">Editer l'événement<small> : <?= htmlentities($event->getTitle()); ?></small></h1>
                <form method="POST" action="" class="form">
                    <div class="row mt-3">
                        <div class="col-md-12">
                            <input type="text" class="form-control" id="title" name="title" required value="<?= isset($data['title']) ? htmlentities($data['title']) : '' ?>" placeholder="Titre de l'événement">
                            <?php if (isset($errors['title'])): ?>
                                <small class="form-text text-muted"><?= $errors['title']; ?></small>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col">
                            <input type="url" name="urlImage" class="form-control" id="urlImage" value="<?= isset($data['urlImage']) ? htmlentities($data['urlImage']) : '' ?>" placeholder="url d'une image déjà en ligne">
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-12">
                            <input type="date" class="form-control" id="date" name="date" required value="<?= isset($data['date']) ? htmlentities($data['date']) : '' ?>">
                            <?php if (isset($errors['date'])): ?>
                                <small class="form-text text-muted"><?= $errors['date']; ?></small>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-12">
                            <select class="browser-default custom-select" id="theme" name="theme">
                                <option selected><?= $t = isset($data['theme']) ? htmlentities($data['theme']) : 'Thème' ?></option>
                                <?php foreach($theme as $t): ?>
                                    <?php $t = substr($t, 1, -1); ?>
                                    <option value="<?= $t ?>"><?= $t ?></option>
                                <?php endforeach; ?>
                                <?php if (isset($errors['theme'])): ?>
                                    <small class="form-text text-muted"><?= $errors['theme']; ?></small>
                                <?php endif; ?>
                            </select>
                        </div>
                    </div>    
                    <div class="row mt-3">
                        <div class="form-group col-md-6">
                            <input type="time" class="form-control" id="start" name="start" placeholder="HH:MM" required value="<?= isset($data['start']) ? htmlentities($data['start']) : '' ?>">
                            <?php if (isset($errors['start'])): ?>
                                <small class="form-text text-muted"><?= $errors['start']; ?></small>
                            <?php endif; ?>
                        </div>
                        <div class="form-group col-md-6">
                            <input type="time" class="form-control" id="end" name="end" placeholder="HH:MM" required value="<?= isset($data['end']) ? htmlentities($data['end']) : '' ?>">
                        </div>
                    </div>    
                    <div class="row mt-3">
                        <div class="col">
                            <textarea name="content" class="form-control" id="content" placeholder="Description"><?= isset($data['content']) ? htmlentities($data['content']) : '' ?></textarea>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col">
                            <input type="text" class="form-control" name="adress" id="adress" placeholder="Adresse" required value="<?= isset($data['adress']) ? htmlentities($data['adress']) : '' ?>">
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="zipcode" id="zipcode" placeholder="Code Postal" required value="<?= isset($data['zipcode']) ? htmlentities($data['zipcode']) : '' ?>">
                        </div>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="city" id="city" placeholder="Ville" required value="<?= isset($data['city']) ? htmlentities($data['city']) : '' ?>">
                        </div>
                    </div>
                    <button class="btn btn-dark my-3">
                        <a href="<?= route_to_url('calendar') ?>"><i class="fas fa-undo fa-2x"></i> Annuler</a>
                    </button>
                    <button type="submit" class="btn btn-blue-grey my-3">
                        <i class="fas fa-check fa-2x"></i> Enregistrer
                    </button>
                    <button class="btn my-3">
                        <a href="<?= route_to_url('currentEvent') ?>?id=<?= $event->getId(); ?>"><i class="far fa-eye fa-2x"></i> Visualiser</a>
                    </button>
                    <input type="hidden" name="token" id="token" value="<?= $token; ?>" />
                    <button class="btn btn-danger my-3">
                        <a href="<?= route_to_url('delete') ?>?delete=<?= $event->getId() . "&token=" . $token ?>" name="delete"><i class="fas fa-times fa-2x"></i> Supprimer</a>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>