<div class="jumbotron jumbotron-fluid text-white bg-Altair-grey">
    <div class="container-fluid">
        <div>    
            <h1 class="text-center card-title" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">Les évènements</h1>
        </div>
        <?php
            foreach($allEvents as $events){
              $eventName = (empty($events['name'])) ? '' : $events['name'];
              $eventPlace = (empty($events['place']['name'])) ? '' : $events['place']['name'];
              $eventLocation = (empty($events['place']['location'])) ? '' : $events['place']['location'];
              $eventDescription = (empty($events['description'])) ? '' : $events['description'];
              $eventPicture = (empty($events['cover']['source'])) ? '' : $events['cover']['source'];
              $eventStartTime = (empty($events['start_time'])) ? '' : $events['start_time'];
              $eventStart = new DateTime($eventStartTime);
              $date = $eventStart->format('d-m-Y');
              $hour = $eventStart->format('H:i');
              $id = $events['id'];
        ?>
        <div class="row mb-3">
            <div class="col-md-6">
                <div class="card card-grey-2 p-4 cardEvent">
                    <h3><?= $eventName ?></h3>
                    <h3 class="card-title">
                        <?= htmlentities(ucwords($date)); ?>
                    </h3>
                    <h5 class="card-title"><i class="far fa-compass"></i>&nbsp;<?= $eventPlace. ' ' .$eventLocation['street']. ' ' .$eventLocation['city'] ?></h5>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card card-grey-2 p-4 cardEvent">
                    <img src="<?= $eventPicture; ?>" alt="<?= $eventName ?>" class="card-img img-fluid">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card card-grey-2 p-4 cardEvent">
                    <p><?= htmlentities($eventDescription); ?></p>
                </div>
            </div>
        </div>
        <button type="button" class="btn-floating btn-lg btn-fb infobulle mr-2">
            <a href="https://www.facebook.com/events/<?= $id ?>" class="text-white"><i class="fab fa-2x fa-facebook"></i></a>
            <span class="tooltip">Visualiser</span>
        </button>
        <button type="button" class="btn-floating btn-lg btn-fb infobulle">
            <a href="http://m.me/AltairStrategieEtFormationEnCommunication" class="text-white"><i class="fab fa-2x fa-facebook-messenger"></i></a>
            <span class="tooltip">Contacter</span>
        </button>
    </div>
</div>
<?php
}
   

        