<div style="text-align:center; text-transform: uppercase; background: #242526; color: #e4e6eb; margin: 2%; padding: 2%; border-radius: 0.5rem; box-shadow: 1px 2px 10px black;">
  <h1 style="text-shadow: 1px 2px 10px black;">Les évènements</h1>
</div>
<?php
    foreach($allEvents as $events){
      $eventName = (empty($events['name'])) ? '' : $events['name'];
      $eventPlace = (empty($events['place']['name'])) ? '' : $events['place']['name'];
      $eventDescription = (empty($events['description'])) ? '' : $events['description'];
      $eventPicture = (empty($events['cover']['source'])) ? '' : $events['cover']['source'];
      $eventStartTime = (empty($events['start_time'])) ? '' : $events['start_time'];
      $eventStart = new DateTime($eventStartTime);
      $date = $eventStart->format('d-m-Y');
      $hour = $eventStart->format('H:i');
      $id = $events['id'];
?>
    <div style="background: #242526; margin: 2%; border-radius: 0.5rem; text-align:center; padding: 2%; color: #e4e6eb;">
        <div style="background: #3a3b3c; margin: 2%; border-radius: 0.5rem; padding: 2%; box-shadow: 1px 2px 10px black;"> 
            <h2><?= $eventName ?></h2>
        </div>
        <div style="background: #3a3b3c; margin: 2%; border-radius: 0.5rem; padding: 2%; box-shadow: 1px 2px 10px black; font-size: 1.2em;">
            <h2>
              <?= $date ?> à partir de <?= $hour ?>
            </h2>
            <p style="max-width: 50vw; margin: auto; padding:2%;">
              <?= $eventDescription ?>
            </p>
            <img style="border-radius: 0.5rem; box-shadow: 1px 2px 10px black; height: 500px; margin-top: 2%; padding: .5%; border: 4px dashed #e4e6eb" src="<?= $eventPicture ?>" alt="">
        </div>
        <button type="button" class="btn-floating btn-lg btn-fb infobulle mr-2">
            <a href="https://www.facebook.com/events/<?= $id ?>" class="text-white"><i class="fab fa-facebook-f"></i></a>
            <span class="tooltip">Visualiser</span>
        </button>
        <button type="button" class="btn-floating btn-lg btn-fb infobulle">
            <a href="https://m.me/Lacasadibino" class="text-white"><i class="fab fa-facebook-messenger"></i></a>
            <span class="tooltip">Contacter</span>
        </button>
    </div>
<?php
}