<div class="jumbotron jumbotron-fluid text-white bg-Altair-grey">
    <div class="row justify-content-center">
        <div class="col-8">
            <img src="<?= URL_SOURCES."/images/creative-light.jpg"?>" alt="" style="width: 100%; height: 150px; border-radius: 20px; position: relative;">
        </div>
        <div class="col-8 d-flex justify-content-center">
            <img src="<?= $admin['image'] ?>" class="card-img img-fluid" alt="photo de profil de <?= $admin['lastname'] ?>" style="width: 200px; height: 200px; position: absolute; top:-175px;">
        </div>
    </div>
    <div class="row justify-content-center mt-4">
        <div class="col-10 d-flex justify-content-center">
            <h2 class="monthTitle"><?= $admin['firstname']. ' ' .(strtoupper($admin['lastname'])) ?></h2>
        </div>    
        <div class="col-4 d-flex justify-content-around customLink">
            <a href="<?= $admin['facebook'] ?>" class="px-2 fa-lg li-fb"><i class="fab fa-lg fa-facebook"></i></a>
            <a href="<?= $admin['linkedin'] ?>" class="px-2 fa-lg li-ic"><i class="fab fa-lg fa-linkedin-in"></i></a>
            <a href="<?= $admin['viadeo'] ?>" class="px-2 fa-lg tw-ic"><i class="fab fa-lg fa-viadeo"></i></a>
            <a href="<?= $admin['skype'] ?>" class="px-2 fa-lg tw-ic"><i class="fab fa-lg fa-skype"></i></a>
        </div>
    </div>
    <div class="row justify-content-center my-5 mh-100">
        <div class="col-xl-8 col-sm-12">
            <div class="row">
                <div class="col-xl-5 col-sm-12">
                    <div class="card-grey-2 p-4 h-100">
                        <h5 class="text-grey">Présentation</h5>
                        <div class="list-group">
                            <div class="row">
                                <div class="col-md-12">
                                    <h5><?= (empty($admin['work'])) ? 'Profession, entreprise' : $admin['work'] ?></h5>
                                    <h5><?= (empty($admin['diplome'])) ? 'Diplôme' : $admin['etude'] ?></h5>
                                    <h5><?= (empty($admin['etudes'])) ? 'Études' : $admin['etude'] ?></h5>
                                    <h5><?= (empty($admin['ville'])) ? 'Ville' : $admin['ville'] ?></h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-5 offset-md-2 col-sm-12">
                    <div class="card-grey-2 p-4 h-100">
                        <h5 class="text-grey">Coordonnées</h5>
                        <div class="list-group">
                            <div class="row">
                                <div class="col-md-12">
                                    <h5>Adresse</h5>
                                    <h5><?= (empty($admin['telephone'])) ? 'Téléphone' : $admin['telephone'] ?></h5>
                                    <h5><?= (empty($admin['email'])) ? 'Email' : $admin['email'] ?></h5>
                                    <h5><?= (empty($admin['website'])) ? 'Website' : $admin['website'] ?></h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-xl-6 col-sm-12 my-2">
            <?php 
                foreach ($events as $event):
                        $data = $event['start'];
                        $data = new DateTime($data);
                        $eventStart = $data->format('Y-m-d');
                        $date = $data->format('Y/m/d');
                        setlocale(LC_TIME, "fr_FR", "French");
                        $date = strftime("%A %d %B %G", strtotime($date));
                        $date = ucwords($date);
                    if ($today <= $event['start']):
                        $isValide = $event;?>
                            <div class="row mb-3 mh-100">
                                <div class="col-md-8 my-2">
                                    <div class="card card-grey-2 p-4 justify-content-between h-100">
                                        <span><i class="fas fa-circle text-<?= $isValide['themeColor'] ?>"></i>&nbsp; <?= $date ?></span>
                                        <h3 class="titleEvent"><?= $isValide['title'] ?></h3>
                                        <span>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="1.4em" height="1.2em" viewBox="0 0 20.01 20" class="mr-2"><defs><style>.cls-2{fill:#acacac;}</style></defs><g id="Calque_2" data-name="Calque 2"><g id="Calque_1-2" data-name="Calque 1"><path class="cls-2" d="M10,0A10,10,0,1,0,20,10,10,10,0,0,0,10,0Zm0,19.35A9.35,9.35,0,1,1,19.36,10,9.35,9.35,0,0,1,10,19.35Z"/><path class="cls-2" d="M15.1,4.49,7.6,7.42a.32.32,0,0,0-.18.18L4.49,15.1a.31.31,0,0,0,.07.34.29.29,0,0,0,.23.1l.11,0,7.5-2.94a.34.34,0,0,0,.19-.18l2.93-7.5a.31.31,0,0,0-.07-.34A.32.32,0,0,0,15.1,4.49ZM12,12,5.36,14.65,8,8l6.68-2.62Z"/><rect class="cls-2" x="9.68" y="2.02" width="0.65" height="1.61"/><rect class="cls-2" x="9.68" y="16.37" width="0.65" height="1.61"/><rect class="cls-2" x="2.02" y="9.68" width="1.61" height="0.65"/><rect class="cls-2" x="16.37" y="9.68" width="1.61" height="0.65"/><path class="cls-2" d="M10,10.65a.65.65,0,0,0,.65-.65.65.65,0,1,0-.65.65Z"/></g></g></svg>   
                                        <?= $isValide['adress'].' '.$isValide['zipcode'].' '.$isValide['city'] ?></span>
                                    </div>
                                </div>
                                <div class="col-md-4 mh-100 my-2">
                                    <div class="card card-grey-2 h-100">
                                        <img src="<?= $isValide['urlImage'] ?>" alt="<?= $isValide['title'] ?>" class="card-img img-fluid h-100">
                                    </div>
                                </div>
                            </div>
                    <?php endif;
                endforeach;
            ?>
        </div>
    </div>
</div>