<div id="postsList" class="w-100 mb-3">
<?php 
    foreach($data as $d) : 
        // var_dump($d);
        // $caption = $d->caption;
        // $caption = explode('#', $caption);
        // foreach($caption as $key => $c) :        
            // if(preg_match('/altair/', $c, $matches)){
                ?>
                <div class="post">
                    <?php
                    if($d->media_type === 'VIDEO'){
                    ?> 
                        <video controls>
                            <source src="<?= $d->media_url ?>">
                        </video>
                    <?php 
                    }else{
                    ?>  
                        <img src="<?= $d->media_url ?>">
                    <?php
                    }
                    ?>
                    <p><?= $d->caption ?></p>
                    <?php
                ?>
                </div>
                <?php                
            // }
        // endforeach;
     endforeach; ?>
</div>
<div class="d-flex justify-content-center mb-5">
    <form action="<?= route_to_url('instagram') ?>?previous" method="GET">
        <button type="submit" id="preview" class="btn btn-info" name="previous">&lt;</button>
    </form>
    <form action="<?= route_to_url('instagram') ?>?next" method="GET">
        <button type="submit" id="next" class="btn btn-info" name="next">&gt;</button>
    </form>
</div>