<form class="form-inline float-right mt-5 mr-5" action="<?= route_to_url('instagram') ?>?hashtag" method="POST">
        <input class="form-control mr-sm-2" type="search" placeholder="Rechercher" name="search_hashtag" aria-label="Search">
        <button class="btn btn-info" type="submit" name="form_submit">
            <i class="fas fa-search fa-lg"></i>
        </button>
    </form>
<div id="postsList" class="w-100 mb-3">
<?php 
    foreach($data as $d) : 
        $caption = $d->caption;
        $result = stristr($caption, "#");
        // var_dump($result);
        // $caption = explode('#', $caption);
        // foreach($caption as $key => $c) :        
            // if(preg_match('/altair/', $c, $matches)){
                ?>
                <div class="post">
                    <?php
                    if($d->media_type === 'VIDEO'){
                    ?> 
                        <video controls>
                            <source src="<?= $d->media_url ?>">
                        </video>
                    <?php 
                    }else{
                    ?>  
                        <img src="<?= $d->media_url ?>">
                    <?php
                    }
                    ?>
                    <p><?= $d->caption ?></p>
                    <?php
                ?>
                </div>
                <?php                
            // }
        // endforeach;
     endforeach; ?>
</div>
<div class="d-flex justify-content-center mb-5">
    <form action="<?= route_to_url('instagram') ?>?previous" method="GET">
        <button type="submit" id="preview" class="btn btn-info" name="previous">&lt;</button>
    </form>
    <form action="<?= route_to_url('instagram') ?>?next" method="GET">
        <button type="submit" id="next" class="btn btn-info" name="next">&gt;</button>
    </form>
</div>