<div class="text-center d-flex align-items-center justify-content-center myCards" style="background: url(<?= URL_SOURCES."/images/events/book-4126483_1920.jpg"?>); filter: blur(.8); color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>; background-size: cover; background-position: center;">
    <div class="container-fluid my-5">
        <div style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor']."d9" ?>;">
            <div >
                <h4 class="text-center" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: <?= $GLOBALS['STYLE']['titleTextShadow'] ?>;">MES EVENEMENTS</h4>
                <div class="table-reponsive-sm">
                    <table class="table" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'] ?>; color: <?= $GLOBALS['STYLE']['textColor'] ?>; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>;">
                        <thead>
                            <tr>
                                <th scope="col">Évènements</th>
                                <th scope="col">Date</th>
                                <th scope="col">Heure de début - Heure de fin</th>
                                <th scope="col">Nombres d'inscrits</th>
                                <?php if($_SESSION['auth']['role'] === 'superAdmin' || $_SESSION['auth']['role'] === 'admin') : ?>
                                    <th scope="col">Éditer</th>
                                <?php endif; ?>
                            </tr>
                        </thead>
                <?php foreach ($result as $event) : ?>
                    <?php $eid = $event['id']; 
                        $participants = $currentEvent->registerCount($eid);
                    ?>
                        <tbody>
                            <tr>
                                <td><a href="<?= route_to_url('currentEvent') ?>?id=<?= $event['id']; ?>"><?= strtoupper($event['title'])?></a></td>
                                <td><?= (new DateTime($event['start']))->format('d-m-Y') ?></td>
                                <td><?= (new DateTime($event['start']))->format('H:i') ?> - <?= (new DateTime($event['end']))->format('H:i') ?></td>
                                <?php foreach ($participants as $participant): ?>
                                    <td><?= $participant ?></td>
                                <?php endforeach; ?>
                                <?php if ($event['id_admin'] === $_SESSION['auth']['id']): ?>
                                    <td>
                                        <a href="<?= route_to_url('editEvent') ?>?id=<?= $event['id']; ?>" style="color:burlywood!important;">
                                            <svg aria-hidden="true" width="2em" height="2em" focusable="false" data-prefix="fas" data-icon="edit" class="svg-inline--fa fa-edit fa-w-18" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="currentColor" d="M402.6 83.2l90.2 90.2c3.8 3.8 3.8 10 0 13.8L274.4 405.6l-92.8 10.3c-12.4 1.4-22.9-9.1-21.5-21.5l10.3-92.8L388.8 83.2c3.8-3.8 10-3.8 13.8 0zm162-22.9l-48.8-48.8c-15.2-15.2-39.9-15.2-55.2 0l-35.4 35.4c-3.8 3.8-3.8 10 0 13.8l90.2 90.2c3.8 3.8 10 3.8 13.8 0l35.4-35.4c15.2-15.3 15.2-40 0-55.2zM384 346.2V448H64V128h229.8c3.2 0 6.2-1.3 8.5-3.5l40-40c7.6-7.6 2.2-20.5-8.5-20.5H48C21.5 64 0 85.5 0 112v352c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V306.2c0-10.7-12.9-16-20.5-8.5l-40 40c-2.2 2.3-3.5 5.3-3.5 8.5z"></path></svg>
                                        </a>
                                    </td>
                                <?php endif; ?>
                            </tr>
                <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>