<div class="d-flex flex-direction-column align-items-center justify-content-center" style="background: url(<?= URL_SOURCES."/images/success.jpg" ?>); background-size: cover;">
    <div class="container my-5" style="background-color: <?= $GLOBALS['STYLE']['boxBackgroundColor'].'d9' ?>">
        <div class="row justify-content-center pt-5">
                <h2 class="card-title" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: 2px 2px 3px #000000;">Le / les coachs : </h2>
            </div>
        <div class="card-deck mt-5 p-3">
        <?php foreach($coachs as $coach): ?>
            <?php if (!empty($_GET['filter'])):
                $id = $coach['coach_id']; 
            ?>
            <?php else : ?>
            <?php $id = $coach['id'];
            ?>
            <?php endif; ?>
            <?php 
                $coachAll = $coachEvents->myCreatedEvents($id);
                $coachInfos = $coachInfo->getAdminCoaching($id);
            ?>
            <div id="card-1" class="card text-center" style="background-color: transparent; color: <?= $GLOBALS['STYLE']['textColor'] ?>; ">
                <img src="<?= $coach['image'] ?>" class="card-img-top" alt="photo du coach <?= $coach['lastname']?>">
                <div class="card-body">
                    <a href="<?= route_to_url('fullAccount') ?>?id=<?= $id?>" class="list-group-item list-group-item-action bg-light mt-2 rounded">
                        <h5 class="card-title"><?= $coach['firstname'].' '.$coach['lastname']?></h5>
                        <?php if (!empty($coachInfos)) : ?>
                                <h5 class="card-title"><?= ucwords($coachInfos['coachingDo']) ?></h5>
                                <h6 class="card-text"><?= $coachInfos['categorie'] ?></h6>
                        <?php endif; ?>
                    </a>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <div class="row my-5">
            <div class="col-sm-12">
                <div class="card text-center" style="box-shadow: <?= $GLOBALS['STYLE']['boxShadow'] ?>; background-color: transparent; color: black; font-size: <?= $GLOBALS['STYLE']['textFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['textFontFamily'] ?>;">
                    <div class="card-body">
                        <div class="col-12 mt-4">
                            <h2 class="card-title" style="color: <?= $GLOBALS['STYLE']['titleColor'] ?>; font-size: <?= $GLOBALS['STYLE']['titleFontSize'] ?>; font-family: <?= $GLOBALS['STYLE']['titleFontFamily'] ?>; text-shadow: 2px 2px 3px #000000;">Le / les évènements : </h2>
                            <?php if (!empty($events)) : ?>
                                <?php foreach($events as $event): ?>
                                <div class="list-group col-12">
                                    <a href="<?= route_to_url('currentEvent') ?>?id=<?= $event['id']?>" class="list-group-item list-group-item-action bg-light mt-2 rounded">
                                        <div class="text-center">
                                            <h5 class="card-title"><?= $event['title'] ?></h5>
                                            <h6 class="card-title"><?= $event['content'] ?></h6>
                                        </div>
                                    </a>
                                </div>
                                <?php endforeach; ?>
                            <?php else : ?>
                                <p>Aucun Résultat</p>
                            <?php endif; ?>
                            <a href="<?= route_to_url('calendar') ?>" class="btn grey darken-1 mt-2">Retour</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>